### ISSUE TITLE
How to get Amazon dataset preprocessing code?

### ISSUE THREAD

**Issue by Wenjun-Peng** [Shawn-hub-hit/GraphSRRL-master#1]
It is really time-consuming to write preprocessing code for Amazon dataset. Could you please give me it?

**Comment by Shawn-hub-hit** [comment]
There is a preprocessing script in ./utils.

**Comment by Shawn-hub-hit** [comment]
> It is really time-consuming to write preprocessing code for Amazon dataset. Could you please give me it?

There is a preprocessing script in ./utils.

**Comment by Wenjun-Peng** [comment]
> > It is really time-consuming to write preprocessing code for Amazon dataset. Could you please give me it?
> 
> There is a preprocessing script in ./utils.

I mean code for Amazon Dataset which is one of experiment in your paper. the code in ./utils is for CIKM

**Comment by Shawn-hub-hit** [comment]
> > > It is really time-consuming to write preprocessing code for Amazon dataset. Could you please give me it?
> > 
> > 
> > There is a preprocessing script in ./utils.
> 
> I mean code for Amazon Dataset which is one of experiment in your paper. the code in ./utils is for CIKM

OK, I have upload the preprocessing code for Amazon Dataset in ./utils/2-preprocess-AmazonReview.py for your reference.

**Comment by Shawn-hub-hit** [comment]
> > > It is really time-consuming to write preprocessing code for Amazon dataset. Could you please give me it?
> > 
> > 
> > There is a preprocessing script in ./utils.
> 
> I mean code for Amazon Dataset which is one of experiment in your paper. the code in ./utils is for CIKM

OK, I have uploaded the preprocessing code for Amazon Dataset in ./utils/2-preprocess-AmazonReview.py for your reference.

**Comment by Wenjun-Peng** [comment]
> > > > It is really time-consuming to write preprocessing code for Amazon dataset. Could you please give me it?
> > > 
> > > 
> > > There is a preprocessing script in ./utils.
> > 
> > 
> > I mean code for Amazon Dataset which is one of experiment in your paper. the code in ./utils is for CIKM
> 
> OK, I have uploaded the preprocessing code for Amazon Dataset in ./utils/2-preprocess-AmazonReview.py for your reference.

Thanks! It is help me a lot
