### ISSUE TITLE
Need pre-processing codes for Amazon dataset, which cannot be found in utils folder

### ISSUE THREAD

**Issue by CDboyOne** [Shawn-hub-hit/GraphSRRL-master#2]
There are only pre-processing codes for CIKM dataset in ./utils folder.

**Comment by Shawn-hub-hit** [comment]
> There are only pre-processing codes for CIKM dataset in ./utils folder.

I have uploaded the preprocessing code for Amazon Dataset in ./utils/2-preprocess-AmazonReview.py for your reference.
